### ISSUE TITLE
Best way to access Swiper API  

### ISSUE THREAD

**Issue by geckoslair** [ksachdeva/angular-swiper#1]
Hi Kapil, I would like to ask you the best way to access the nolimits4web/swiper API directly from an angular controller. Thanks for your attention. Enrico.

**Comment by ksachdeva** [comment]
Hi Enrico,
Currently the only way to interact from controller would be to pass the properties (e.g. initialSlide, loop, slides-per-view etc) as part of scope to the template/directive.

That being said, the right way of doing is by exposing it is as a service that you can inject in your controller. I intended to work on this part. Would make it available soon.

**Comment by geckoslair** [comment]
Thanks!

**Comment by ksachdeva** [comment]
There is now a way to do 2-way binding. Currently the approach is not using the notion of exposing it as a service but it seems to work.
