### ISSUE TITLE
slideTo

### ISSUE THREAD

**Issue by vinodhum** [ksachdeva/angular-swiper#10]
I am trying $scope.swiper.slideTo(4); but it says slideTo is not a function
any idea what am I missing

**Comment by ksachdeva** [comment]
just tried it seems to be working for me. most likely you are not providing / initializing your swiper object

See below code - 

module.controller('TestCtrl', function($scope) {
            $scope.swiper = {};
            $scope.next = function() {
                $scope.swiper.slideNext();
            };
        });
