### ISSUE TITLE
re-initialize after data has changed

### ISSUE THREAD

**Issue by marcheluis** [ksachdeva/angular-swiper#13]
Is there any way to update the slider with new data after a $http request? I am using ng-repeat to iterate through the data i get from the $http request, however the view doesn't get updated after the initial request.

**Comment by iDuuck** [comment]
@marcheluis Could you share your solution?

**Comment by brh55** [comment]
You should be able to set a watch on the model for updates and then within the callback, execute swiper's update method. You could even append the updates, but a caveat might be the slide index if you are using that.

**Comment by dmastag** [comment]
For anyone who ever has this issue, here is a codepen implementing @brh55 solution

http://codepen.io/dmastag/pen/zqzWGK
