### ISSUE TITLE
Compatibilty with Angular2

### ISSUE THREAD

**Issue by prijindal** [ksachdeva/angular-swiper#30]
Any plans to make it compatible with the new angular version??

**Comment by ksachdeva** [comment]
Just pushed an example angular 2 application using swiper. Will updating it with more examples (and features in coming days)

https://github.com/ksachdeva/angular2-swiper-example

Will later extract the component in its own project (have to figure out how to publish typescript based modules first)

**Comment by ksachdeva** [comment]
Ok. Figured out how to write npm modules that have been written using typescript.

https://github.com/ksachdeva/angular2-swiper contains the swiper component for Angular 2
https://github.com/ksachdeva/angular2-swiper-example contains the example that makes use of swiper component
