### ISSUE TITLE
Swiper is not defined

### ISSUE THREAD

**Issue by Triplecorpse** [ksachdeva/angular-swiper#46]
I downloaded angular-swiper, included './bower_components/angular-swiper/dist/angular-swiper.js' after angular.js but before my scripts, copy-pasted you markup in tutorial and I have an error.
Almost forgot. I don't have swiper.min.css to include to my html.
![2016-07-27 1](https://cloud.githubusercontent.com/assets/11461770/17183316/a62a3cfa-542f-11e6-9850-b2ae917e53ba.png)

**Comment by ksachdeva** [comment]
You may be missing installation of swiper library - bower install swiper

**Comment by Triplecorpse** [comment]
Omg, sorry for bothering with such thing :) You were right, everything work fine now
