### ISSUE TITLE
Can we get support for centeredSlides?

### ISSUE THREAD

**Issue by scurk1415** [ksachdeva/angular-swiper#49]
Well as the title says, can you add the support for centeredSlides parameter?

**Comment by naumanahmed19** [comment]
I am also looking for this

**Comment by scurk1415** [comment]
ok just realized that we can pass `override-parameters="{'centeredSlides': true}"` into `ks-swiper-container` and it works

**Comment by brh55** [comment]
@scurk1415 @ksachdeva  can you please close this issue as any additional settings can be applied with the override-parameters object param.
