### ISSUE TITLE
Two-Way Binding of Swiper problem

### ISSUE THREAD

**Issue by sebrojas14** [ksachdeva/angular-swiper#5]
I was trying to listen to an event, so I first tried the example:

`<ks-swiper-container swiper="rosesSwiper" loop="true" slides-per-view="1">`
`      <ks-swiper-slide class="swiper-slide" ng-repeat="rose in roses">`
`        <div class="imgFullWu" style="background: url(img/roses/{{rose.id}}.jpg);"></div>`
`        <div class="t_rose">`
`          <h1>{{rose.title}}</h1>`
`          <p>{{rose.description}}</p>`
`          <button class="boton_g" ng-click="selectRose(rose.id)">`
`           Regalar`
`          </button>`
`        </div>`
`      </ks-swiper-slide>`
`    </ks-swiper-container>`

`.controller('RosesCtrl', function($rootScope, $scope, $ionicModal, $state, generalService) {  `
`  $scope.rosesSwiper = {};  `
`  generalService.GetRoses(function (roses) {`
`      $scope.roses = roses;`
`  });  `
`  $scope.selectRose = function () {         `
`    $scope.rosesSwiper.slideNext();`
`  };`
`})`

And I get TypeError: $scope.rosesSwiper.slideNext is not a function

**Comment by ksachdeva** [comment]
Hi Sebrojas,

You are not providing the controller that manages "swiper" to the directive. I have updated the demo/index.html to show how to use it.

Regards
Kapil

**Comment by sebrojas14** [comment]
Is not clear for me...I'm using Ionic, and the view has already a controller, so...

**Comment by ksachdeva** [comment]
Hi Sebrojas,

The controller of your view needs to have the swiper object in its $scope. Provide me the snippet of ionic view code and may be it will clear up what may be wrong.

Also try running the demo app by performing following steps -
git clone <repo>
npm install
bower install
gulp serve

then in your browser go to demo/index.html ... I have put an example for 2 way binding in this demo.

**Comment by sebrojas14** [comment]
The view

`<ion-view view-title="">
  <ion-pane>
    <ks-swiper-container swiper="rosesSwiper" loop="true" show-nav-buttons="true" slides-per-view="1" pagination-is-active="true">
      <ks-swiper-slide class="swiper-slide" ng-repeat="rose in roses">
        <div class="full">
          <div class="full-part imgFullW" style="background: url(img/roses/{{rose.id}}.jpg);">&nbsp;</div>
          <div class="full-part">
            <div class="v-centered-content t_rose">
              <h1>{{rose.title}}</h1>
              <p>{{rose.description}}</p>
              <button class="boton_g" ng-click="next()">
               Regalar
              </button>
            </div>
          </div>
          <div class="full-part full-part-pagination"></div>
        </div>
      </ks-swiper-slide>
    </ks-swiper-container>
  </ion-pane>
</ion-view>
`

The controller:

`.controller('RosesCtrl', function($rootScope, $scope, $ionicModal, $state, generalService) {
  
  $scope.rosesSwiper = {};
  
//this works
  $scope.next = function(){
    $scope.rosesSwiper.slideNext();
  };
  

//this doesn't works, obviosly, $scope.rosesSwiper is {}...so when I have to put the event listener?
  $scope.rosesSwiper.on('slideChangeStart', function () {
      
    alert('slideChangeStart');
  });
})`

**Comment by ksachdeva** [comment]
Hi Sebrojas,

Not able to see where you are specifying your controller ?

try this -
<ion-view view-title="" ng-controller="RosesCtrl">
</ion-view>

**Comment by sebrojas14** [comment]
@ksachdeva the controller in Ionic is specified in the state configuration:

`.config(function($stateProvider, $urlRouterProvider) {`
`  $stateProvider`
`    .state('app', {`
`    url: '/app',`
`    abstract: true,`
`    templateUrl: 'templates/menu.html',`
`    controller: 'AppCtrl'`
`  })`
`   .state('app.roses', {`
`      url: '/roses',`
`      views: {`
`        'menuContent': {`
`          templateUrl: 'templates/roses.html',`
`          controller: 'RosesCtrl'`
        }`
      }`
    });`
  // if none of the above states are matched, use this as the fallback`
  $urlRouterProvider.otherwise('/app/roses');`
});`

**Comment by hrpatidar** [comment]
Hi Sebrojas,

I am doing the same thing which you have done above. 

But I am always getting undefined this object $scope.rosesSwiper. Not able to call slideNext or slideTo. 

coming $scope.rosesSwiper.slideNext() is not a function. 

Please help me out.

Thanks

**Comment by sebrojas14** [comment]
I ended using the new slide-box of ionic http://ionicframework.com/docs/api/directive/ionSlideBox/

**Comment by juergengunz** [comment]
@ksachdeva 
i have the same issue, as controllers in Ionic are specified in the state configuration.
Is there any chance to make it work like that?

**Comment by najafi-saeed** [comment]
@ksachdeva I have the same issue!
