### ISSUE TITLE
Responsive slider

### ISSUE THREAD

**Issue by sybrendotinga** [ksachdeva/angular-swiper#57]
Hello, 

Thank you for making this cool directive! I have a problem making the slider responsive. I've had a look at the previous issues, and took this as an example, but it did not seem to work.

This is my code:

`<ks-swiper-container
                                override-parameters="{ 'breakpoints': { '320': { 'slidesPerView': '1' }, '640': { 'slidesPerView': '2' }, '768': { 'slidesPerView': '2' }, '1024': { 'slidesPerView': '3' } }}"
                                initial-slide="0" loop="false" show-nav-buttons="true" slides-per-view="3"
                                space-between="50" pagination-hide="true" grab-cursor="true"
                        >`

I'm hoping you can help me with a solution.

**Comment by yahyafakhroji** [comment]
I also experienced the same problem, maybe you need to upgrade `swiper.js` to the latest version.
