### ISSUE TITLE
Example does not work without ng-repeat

### ISSUE THREAD

**Issue by atd** [ksachdeva/angular-swiper#8]
Changing the example to:

```
  <ks-swiper-container initial-slide="3" loop="false" show-nav-buttons="false" slides-per-view="4" space-between="5" pagination-clickable="false">
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/1.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/2.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/3.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/4.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/5.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/1.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/1.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/1.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/1.jpg">
      </ks-swiper-slide>
      <ks-swiper-slide class="swiper-slide">
          <img ng-src="http://api.randomuser.me/portraits/thumb/men/1.jpg">
      </ks-swiper-slide>
  </ks-swiper-container>
```

Only shows one slide

**Comment by dd-kunai** [comment]
Having the very same issue. Trying to work with without `ng-repeat`. Any idea @ksachdeva ?
Thanks in advance

**Comment by dd-kunai** [comment]
Current directive requires `ng-repeat` because is watching for the `$last` element to run.
```
if (scope.$last === true) {
    $timeout(function() {
        containerController.buildSwiper();
    }, 0);
}
```

A good way to solve it would be to pass a param when there is no `ng-repeat` so it simply executes

**Comment by ksachdeva** [comment]
it is now fixed, there is also a demo now; please see the latest

**Comment by KasperAndersson** [comment]
@ksachdeva This fixes doesn't seems to be pushed for npm? Just downloaded this directive via npm, and it still has the ```scope.$last```expression.

**Comment by ksachdeva** [comment]
I have pushed another version but am sure the one on npm was the one with out scope.$last

**Comment by KasperAndersson** [comment]
@ksachdeva I keep getting the version0.0.1, during ```npm install angular-swiper```

**Comment by dideriksn** [comment]
+1

**Comment by ksachdeva** [comment]
Apologies Kasper. I do not know why I was reading 'bower install'. I have not pushed it on 'npm'; do not even recall pushing the first version either. Will take care of it very soon. Sorry again for the confusion.

**Comment by ksachdeva** [comment]
Just tried it and am not able to push. I also verified that I have never pushed it on npm.

https://www.npmjs.com/~staskorz is the user who pushed it on the npm. I will contact him to push the latest release.

**Comment by ksachdeva** [comment]
Hi Kasper, npm now has the latest angular-swiper now. Staskorz was kind enough to delete his package and let me create one

**Comment by KasperAndersson** [comment]
@ksachdeva Thanks! Really nice job.


![Hug](http://i.giphy.com/iHgznkhwC6XYs.gif)
